### ISSUE TITLE
Foyer view link error on demo

### ISSUE THREAD

**Issue by mattparkin** [Stagecast-support/stagecast-help#2]
Clicking on link to view User 2's foyer on this page results in an error: https://stagecast.net/admin/web/index.php?r=foyer%2Findex

**Comment by daverees4** [comment]
I don't think we need test users 2 and 3 - so have deleted them

**Comment by daverees4** [comment]
(if you'd like more test users - please let me know)

**Comment by mattparkin** [comment]
Don't think so! Just logged it as it popped up while demo'ing to Nick, and in case it was a more generic bug…
